### ISSUE TITLE
Asset gets created even though it gives an error

### ISSUE THREAD

**Issue by Technology89** [iotaledger/IOTA-2.0-DevNet-wallet#28]
Creating a Asset i get this error:
"The application is not able to complete the request, due to the following error: Bigger is forbidden, as contains [bigger]"

But the asset is still created.

Windows wallet.

**Comment by DanEvers** [comment]
I have a similar error showing "The application is not able to complete the request, due to the following error: Failed to execute 'text' on 'Response': body stream already read" during creation of the CC.

**Comment by Dr-Electron** [comment]
@Technology89 this is correct behaviour. You are trying to create an asset with a forbidden name. So the asset-registry won't allow it. But local it will still be saved. Just others won't see the name if they receive the token
