### ISSUE TITLE
Why do you use old style react?

### ISSUE THREAD

**Issue by gtgalone** [iotaledger/IOTA-2.0-DevNet-wallet#35]
Why don't use react hooks?

I am just curious.

Is There any reasons?

I have checked that all code are old style react codes.

**Comment by Dr-Electron** [comment]
This is just a dev wallet and mostly developed by backend devs I think ;)
It doesn't need to be top notch design :)

**Comment by gtgalone** [comment]
Oh I got it.

This is not production repo.

Okay Thank you!
